### ISSUE TITLE
The value of the Slice has been Changed!!

### ISSUE THREAD

**Issue by shadowedge** [mactsouk/mastering-Go-3rd#1]
with the line 47 of the code [sliceArrays.go](https://github.com/mactsouk/mastering-Go-3rd/blob/main/ch02/sliceArrays.go),it says:
```go
// This change does not go to S12
a[1] = "-N2-"
```
but Actually, the changes of a[1]  **does go to S12** !

By the way ,  the _Book_ is right: "However, array a and slice S12 are still connected because the capacity of S12 has not
changed."

**Comment by mactsouk** [comment]
@shadowedge You are correct. I have changed the comments in `sliceArrays.go` to reflect what you said.
