### ISSUE TITLE
Where is code for chap 12?

### ISSUE THREAD

**Issue by ScopeSV** [mactsouk/mastering-Go-3rd#12]
Why isn't the code for chap 12 available?

When implementing the `GetRandom` method you are suddenly using a function `method(min, max)`.
Where is this function coming from? What are `min` and `max`?

**Comment by mactsouk** [comment]
@ScopeSV `min` and `max` are the parameters of the `random()` method, which can be found in https://github.com/mactsouk/grpc/blob/main/server/gServer.go

The code of Chapter 12 can be found at https://github.com/mactsouk/grpc

Please let me know if you need anything else.

**Comment by ScopeSV** [comment]
Ah perfect. This didn't come clear in the book. Thank you!
