### ISSUE TITLE
"uninitialized" variables

### ISSUE THREAD

**Issue by TamirFriedman-RecoLabs** [mactsouk/mastering-Go-3rd#3]
When the first argument is non-parseable, the `min`/`max` variables are not initialized to the first parseable argument (but to 0 by default). This would lead to bug when all the parseable arguments share the same sign.
https://github.com/mactsouk/mastering-Go-3rd/blob/5607344dcee39496f4696093df6b62ec8ddcb66b/ch01/cla.go#L23

**Comment by mactsouk** [comment]
@TamirFriedman-RecoLabs Again, you are correct. Thanks for pointing that out.
