### ISSUE TITLE
5 go routines instead of 4 as written in book

### ISSUE THREAD

**Issue by TamirFriedman-RecoLabs** [mactsouk/mastering-Go-3rd#4]
In the book it's written about this code:

> The preceding naively implemented example creates 4 go-routines

However there 5 go-routines created in the actual code (other than `main`) indexed: 0, 1, 2, 3, 4

https://github.com/mactsouk/mastering-Go-3rd/blob/5607344dcee39496f4696093df6b62ec8ddcb66b/ch01/goRoutines.go#L17

**Comment by mactsouk** [comment]
@TamirFriedman-RecoLabs Thanks again!
