### ISSUE TITLE
it's error prone habit to compare not with errors.Is

### ISSUE THREAD

**Issue by TamirFriedman-RecoLabs** [mactsouk/mastering-Go-3rd#7]
https://github.com/mactsouk/mastering-Go-3rd/blob/442798c5c9e5b01150008561f95383c7326734c0/ch04/errorInt.go#L46

**Comment by mactsouk** [comment]
@TamirFriedman-RecoLabs Sorry, I do not completely understand what you are saying. Can you explain a little bit more and maybe create a PR?
