### ISSUE TITLE
refactor

### ISSUE THREAD

**Issue by Nikhil2001** [mactsouk/mastering-Go-3rd#9]
https://github.com/mactsouk/mastering-Go-3rd/blob/f405912e1d54150eb6414afcf7fbbf0a71cd7cb2/ch13/allowed.go#:~:text=f405912e1d-,mastering%2DGo%2D3rd,Go%20to%20file,-mactsouk%20Initial%20Public

**func Same[T comparable](a, b T) bool {
	if a == b {
		return true
	}
	return false
}**

as

_func Same[T comparable](a, b T) bool {
	return a == b
}_

@mactsouk may be not a big deal here as you are explaining about generics?

**Comment by mactsouk** [comment]
@Nikhil2001 you are correct. However, I will not change the code because sometimes, you need to print a message or a long entry. Thanks!
